-- Claude_Agent MVP schema (Step 1)
-- Timestamps are TEXT storing ISO 8601 UTC (e.g. 2026-06-06T12:00:00.000Z),
-- generated by the application layer. updated_at is maintained in app code,
-- NOT by SQLite triggers. activity_log is append-only (no updated_at).

CREATE TABLE IF NOT EXISTS task (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  title      TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memory_index (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  slug       TEXT NOT NULL,
  path       TEXT NOT NULL,
  summary    TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approval (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  action_type TEXT NOT NULL,
  payload     TEXT,
  status      TEXT NOT NULL DEFAULT 'pending',
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS activity_log (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  event_type TEXT NOT NULL,
  detail     TEXT,
  created_at TEXT NOT NULL
);
