-- Claude_Agent MVP schema (Step 1)
-- Timestamps are TEXT storing ISO 8601 UTC (e.g. 2026-06-06T12:00:00.000Z),
-- generated by the application layer. updated_at is maintained in app code,
-- NOT by SQLite triggers. activity_log is append-only (no updated_at).

CREATE TABLE IF NOT EXISTS task (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  title      TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memory_index (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  slug       TEXT NOT NULL,
  path       TEXT NOT NULL,
  summary    TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approval (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  action_type      TEXT NOT NULL,
  payload          TEXT,
  status           TEXT NOT NULL DEFAULT 'pending',
  execution_status TEXT NOT NULL DEFAULT 'not_started',
  executed_at      TEXT,
  execution_error  TEXT,
  result_summary   TEXT,
  undo_json        TEXT,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS activity_log (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  event_type TEXT NOT NULL,
  detail     TEXT,
  created_at TEXT NOT NULL
);

-- Step 9 — local events & reminders. All datetimes are ISO 8601 UTC TEXT,
-- generated/validated by the application layer (see schemas/event, schemas/reminder).
-- event.status is 'scheduled' until soft-archived ('archived'); never hard-deleted.
-- reminder.status is 'active' until 'done' (completed) or 'archived' (filed away);
-- 'done' and 'archived' are distinct meanings and both leave the active views.
CREATE TABLE IF NOT EXISTS event (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  title      TEXT NOT NULL,
  starts_at  TEXT NOT NULL,
  ends_at    TEXT,
  location   TEXT,
  notes      TEXT,
  status     TEXT NOT NULL DEFAULT 'scheduled',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reminder (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  title      TEXT NOT NULL,
  due_at     TEXT NOT NULL,
  notes      TEXT,
  status     TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Step 11 — scheduler-fired notifications. Each (kind, source_id) pair fires
-- at most once (UNIQUE index → INSERT OR IGNORE dedup). status: 'unread'→'read'.
-- updated_at maintained in app code (per project convention).
--
-- Step 22 — `dedup_key` (nullable) is an ADDITIVE column for active-topic triage
-- ('line.active_topic'). Existing kinds (reminder.due/event.soon/line.followup)
-- leave it NULL and keep the (kind, source_id) "fire once ever" behavior. Active
-- topics must RE-fire when NEW evidence appears, so they dedup on a STRING key
-- `active_topic:<id>:<newestEvidenceAtUtc>` via the partial unique index below.
-- For an existing DB the column is added by ensureNotificationDedupColumn() in
-- init.ts (PRAGMA + ALTER ADD COLUMN); the partial index excludes legacy NULL rows.
CREATE TABLE IF NOT EXISTS notification (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  kind       TEXT NOT NULL,
  source_id  INTEGER NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT,
  fire_at    TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'unread',
  dedup_key  TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_source ON notification (kind, source_id);
-- idx_notification_dedup is created by ensureNotificationDedupColumn() in init.ts,
-- AFTER the additive ALTER that adds dedup_key to a pre-existing notification
-- table. Creating it here would fail on an existing DB whose table lacks the
-- column (CREATE TABLE IF NOT EXISTS is a no-op there).

-- Runtime feature flags. key is a short slug (e.g. 'google_calendar_enabled').
-- value is '1' (true) or '0' (false). When a key is absent the env-var default
-- applies. updated_at app-maintained per project convention.
CREATE TABLE IF NOT EXISTS config (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Step 12 — conversational chat agent. Single ongoing thread, persisted across
-- restarts. role: 'user'|'assistant'. actions_json: serialised proposed action
-- ids+types for assistant turns (null for user turns). status: 'active'→
-- 'archived' (soft-archive, never hard-deleted). updated_at app-maintained.
CREATE TABLE IF NOT EXISTS chat_message (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  role         TEXT NOT NULL,
  content      TEXT NOT NULL,
  actions_json TEXT,
  status       TEXT NOT NULL DEFAULT 'active',
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);

-- Step 16 — real memory: durable, recallable facts about the user (name,
-- preferences, relationships, routines, projects). Unlike the 4 markdown memory
-- files (summaries-only invariant), fact CONTENT is recalled directly into the
-- prompt. content: one-sentence fact. keywords: lowercase space-joined tags used
-- for deterministic recall scoring. category: identity|preference|relationship|
-- routine|project|general. pinned=1 facts are ALWAYS recalled (core identity).
-- source: chat|manual|brief. status: 'active'→'archived' (soft-archive via
-- fact.forget, never hard-deleted). updated_at app-maintained.
CREATE TABLE IF NOT EXISTS memory_fact (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  content    TEXT NOT NULL,
  keywords   TEXT NOT NULL DEFAULT '',
  category   TEXT NOT NULL DEFAULT 'general',
  pinned     INTEGER NOT NULL DEFAULT 0,
  source     TEXT NOT NULL DEFAULT 'chat',
  status     TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_memory_fact_status ON memory_fact (status);

-- Step 21 — LINE follow-up watches. A user-approved, scheduled READ-ONLY check
-- over the already-ingested LINE export files. At due_at the scheduler searches
-- exported messages newer than baseline_at for `keywords` (optionally limited to
-- chat_filter) and fires ONE 'line.followup' notification (match count + capped
-- snippets, or an explicit "no new matches"). Creating a watch is the approval-
-- gated act (action type `line_followup.create`); the row itself writes nothing
-- back to LINE and triggers no live LINE automation. keywords is a JSON array of
-- strings. status: 'pending' (not yet checked) -> 'fired' (checked once) or
-- 'cancelled'. baseline_at defaults to creation time. updated_at app-maintained.
CREATE TABLE IF NOT EXISTS line_followup (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  topic       TEXT NOT NULL,
  keywords    TEXT NOT NULL,
  chat_filter TEXT,
  due_at      TEXT NOT NULL,
  baseline_at TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'pending',
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_line_followup_status ON line_followup (status, due_at);

-- Step 22 — Active Intelligence Layer: durable active-topic watch store.
-- Read-only LINE safety: an active topic only ever *reads* exported LINE files
-- via the existing keyword search; it never sends/replies/mutates LINE and never
-- triggers live LINE automation. `updated_at` is app-maintained per project
-- convention. Rows are soft-archived via status='resolved'/'paused', never
-- hard-deleted. `baseline_at` is set by the executor at creation (never trusted
-- from the model). `last_summary` is capped at 200 chars and must never contain
-- raw message bodies beyond that cap.
CREATE TABLE IF NOT EXISTS active_topic (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  title            TEXT NOT NULL,
  source           TEXT NOT NULL,              -- 'line' | 'calendar' | 'mixed' | 'general'
  keywords         TEXT NOT NULL,              -- JSON string array, hydrated to string[] in code
  chat_filter      TEXT,                       -- optional LINE chat-name substring filter; null = all
  status           TEXT NOT NULL DEFAULT 'active', -- 'active' | 'paused' | 'resolved'
  priority         INTEGER NOT NULL DEFAULT 50,
  baseline_at      TEXT NOT NULL,              -- ISO 8601 UTC; only evidence newer than this counts
  last_checked_at  TEXT,                       -- ISO 8601 UTC; last scheduler/evidence pass
  last_evidence_at TEXT,                       -- ISO 8601 UTC; atUtc of newest evidence surfaced
  last_summary     TEXT,                       -- capped ≤200 chars, user-safe; NO raw bodies
  cooldown_minutes INTEGER NOT NULL DEFAULT 30,
  created_from     TEXT NOT NULL,              -- 'chat' | 'manual' | 'scheduler'
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_active_topic_status_source ON active_topic (status, source);
CREATE INDEX IF NOT EXISTS idx_active_topic_baseline ON active_topic (baseline_at);
CREATE INDEX IF NOT EXISTS idx_active_topic_updated ON active_topic (updated_at);
