-- Claude_Agent MVP schema (Step 1)
-- Timestamps are TEXT storing ISO 8601 UTC (e.g. 2026-06-06T12:00:00.000Z),
-- generated by the application layer. updated_at is maintained in app code,
-- NOT by SQLite triggers. activity_log is append-only (no updated_at).

CREATE TABLE IF NOT EXISTS task (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  title      TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memory_index (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  slug       TEXT NOT NULL,
  path       TEXT NOT NULL,
  summary    TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS approval (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  action_type TEXT NOT NULL,
  payload     TEXT,
  status      TEXT NOT NULL DEFAULT 'pending',
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS activity_log (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  event_type TEXT NOT NULL,
  detail     TEXT,
  created_at TEXT NOT NULL
);

-- Step 9 — local events & reminders. All datetimes are ISO 8601 UTC TEXT,
-- generated/validated by the application layer (see schemas/event, schemas/reminder).
-- status is 'scheduled'/'active' until soft-archived ('archived'); never hard-deleted.
CREATE TABLE IF NOT EXISTS event (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  title      TEXT NOT NULL,
  starts_at  TEXT NOT NULL,
  ends_at    TEXT,
  location   TEXT,
  notes      TEXT,
  status     TEXT NOT NULL DEFAULT 'scheduled',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reminder (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  title      TEXT NOT NULL,
  due_at     TEXT NOT NULL,
  notes      TEXT,
  status     TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Step 11 — scheduler-fired notifications. Each (kind, source_id) pair fires
-- at most once (UNIQUE index → INSERT OR IGNORE dedup). status: 'unread'→'read'.
-- updated_at maintained in app code (per project convention).
CREATE TABLE IF NOT EXISTS notification (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  kind       TEXT NOT NULL,
  source_id  INTEGER NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT,
  fire_at    TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'unread',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_source ON notification (kind, source_id);

-- Step 12 — conversational chat agent. Single ongoing thread, persisted across
-- restarts. role: 'user'|'assistant'. actions_json: serialised proposed action
-- ids+types for assistant turns (null for user turns). status: 'active'→
-- 'archived' (soft-archive, never hard-deleted). updated_at app-maintained.
CREATE TABLE IF NOT EXISTS chat_message (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  role         TEXT NOT NULL,
  content      TEXT NOT NULL,
  actions_json TEXT,
  status       TEXT NOT NULL DEFAULT 'active',
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
